export const SELECT_COURSE = 'SELECT_COURSE';
export const SELECT_LESSON = 'SELECT_LESSON';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT = 'LOGOUT';

export const GET_HOME_REQUEST = 'GET_HOME_REQUEST';
export const GET_HOME_FAILURE = 'GET_HOME_FAILURE';
export const GET_HOME_SUCCESS = 'GET_HOME_SUCCESS';

export const GET_ALLCOURSES_REQUEST = 'GET_ALLCOURSES_REQUEST';
export const GET_ALLCOURSES_FAILURE = 'GET_ALLCOURSES_FAILURE';
export const GET_ALLCOURSES_SUCCESS = 'GET_ALLCOURSES_SUCCESS';

export const GET_COURSEDETAILS_REQUEST = 'GET_COURSEDETAILS_REQUEST';
export const GET_COURSEDETAILS_FAILURE = 'GET_COURSEDETAILS_FAILURE';
export const GET_COURSEDETAILS_SUCCESS = 'GET_COURSEDETAILS_SUCCESS';

export const MARK_LESSONCOMPLETE_REQUEST = 'MARK_LESSONCOMPLETE_REQUEST';
export const MARK_LESSONCOMPLETE_FAILURE = 'MARK_LESSONCOMPLETE_FAILURE';
export const MARK_LESSONCOMPLETE_SUCCESS = 'MARK_LESSONCOMPLETE_SUCCESS';

export const GET_MONTHENTRIES_REQUEST = 'GET_MONTHENTRIES_REQUEST';
export const GET_MONTHENTRIES_FAILURE = 'GET_MONTHENTRIES_FAILURE';
export const GET_MONTHENTRIES_SUCCESS = 'GET_MONTHENTRIES_SUCCESS';

export const GET_DAYS_REQUEST = 'GET_DAYS_REQUEST';
export const GET_DAYS_FAILURE = 'GET_DAYS_FAILURE';
export const GET_DAYS_SUCCESS = 'GET_DAYS_SUCCESS';

export const SAVE_DAYS_REQUEST = 'SAVE_DAYS_REQUEST';
export const SAVE_DAYS_FAILURE = 'SAVE_DAYS_FAILURE';
export const SAVE_DAYS_SUCCESS = 'SAVE_DAYS_SUCCESS';

export const SAVE_LOGTIME_REQUEST = 'SAVE_LOGTIME_REQUEST';
export const SAVE_LOGTIME_FAILURE = 'SAVE_LOGTIME_FAILURE';
export const SAVE_LOGTIME_SUCCESS = 'SAVE_LOGTIME_SUCCESS';

export const DELETE_LOGTIME_REQUEST = 'DELETE_LOGTIME_REQUEST';
export const DELETE_LOGTIME_FAILURE = 'DELETE_LOGTIME_FAILURE';
export const DELETE_LOGTIME_SUCCESS = 'DELETE_LOGTIME_SUCCESS';

export const GET_INPROGRESS_REQUEST = 'GET_INPROGRESS_REQUEST';
export const GET_INPROGRESS_FAILURE = 'GET_INPROGRESS_FAILURE';
export const GET_INPROGRESS_SUCCESS = 'GET_INPROGRESS_SUCCESS';

export const GET_COMPLETED_REQUEST = 'GET_COMPLETED_REQUEST';
export const GET_COMPLETED_FAILURE = 'GET_COMPLETED_FAILURE';
export const GET_COMPLETED_SUCCESS = 'GET_COMPLETED_SUCCESS';